/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 管理员登录（签发 JWT） */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前登录用户信息（用于校验 token 有效性） */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hazards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 隐患记录分页列表（含筛选） */
        get: operations["listHazards"];
        put?: never;
        /** 新增隐患记录（默认值/联动逻辑在服务端兜底） */
        post: operations["createHazard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hazards/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 隐患概览统计（按状态/等级计数 + 逾期未整改数） */
        get: operations["getHazardStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hazards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 隐患记录详情 */
        get: operations["getHazard"];
        /** 更新隐患记录（部分字段） */
        put: operations["updateHazard"];
        post?: never;
        /** 删除隐患记录（软删除） */
        delete: operations["deleteHazard"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 责任单位列表（下拉/管理页用，含停用项） */
        get: operations["listUnits"];
        put?: never;
        /** 新增责任单位 */
        post: operations["createUnit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新责任单位 */
        put: operations["updateUnit"];
        post?: never;
        /** 删除责任单位（被隐患引用时拒绝） */
        delete: operations["deleteUnit"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hazard-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 隐患类型全量（每行一个「大类+小类」组合，前端按大类分组展示） */
        get: operations["listHazardTypes"];
        put?: never;
        /** 新增隐患类型（需同时填大类与小类，同一组合唯一） */
        post: operations["createHazardType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hazard-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新隐患类型（被引用的类型只允许修改、不允许删除） */
        put: operations["updateHazardType"];
        post?: never;
        /** 删除隐患类型（被隐患引用的类型拒绝删除） */
        delete: operations["deleteHazardType"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 附件（图片）分页列表（含隐患引用次数，可只看未引用） */
        get: operations["listImages"];
        put?: never;
        /** 上传图片（SHA-256 摘要去重：同图返回既有 uuid，不重复保存） */
        post: operations["uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取原图（按 uuid） */
        get: operations["getImage"];
        put?: never;
        post?: never;
        /** 删除附件（连同落盘文件与缩略图；被隐患引用时拒绝 409） */
        delete: operations["deleteImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/{id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取缩略图（缺失时回退原图） */
        get: operations["getImageThumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description 错误码，如 INVALID_CREDENTIALS / NOT_FOUND / VALIDATION_ERROR */
            code: string;
            /** @description 人类可读错误信息 */
            message: string;
        };
        LoginRequest: {
            /** @example admin */
            username: string;
            /**
             * Format: password
             * @example ********
             */
            password: string;
        };
        LoginResponse: {
            /** @description JWT 访问令牌 */
            token: string;
            user: components["schemas"]["UserInfo"];
        };
        UserInfo: {
            username: string;
            /**
             * @description admin=管理用户；mini=小程序用户（预留）
             * @enum {string}
             */
            userType: "admin" | "mini";
        };
        /** @enum {string} */
        HazardStatus: "待整改" | "整改受阻" | "已整改";
        /** @enum {string} */
        HazardLevel: "一般隐患" | "重大隐患";
        Hazard: {
            /** Format: int64 */
            id: number;
            /** @description 检查区域 */
            inspectionArea: string;
            /**
             * Format: date
             * @description 检查日期 YYYY-MM-DD
             */
            inspectionDate: string;
            /** @description 检查人员 */
            inspector: string;
            /** @description 隐患描述 */
            description: string;
            /** @description 建议整改方案 */
            suggestion?: string | null;
            /**
             * Format: int64
             * @description 责任单位 id
             */
            unitId: number;
            /** @description 责任单位名称（JOIN 返回） */
            unitName: string;
            /** @description 责任人（单位冗余快照） */
            person: string;
            /**
             * Format: date
             * @description 要求完成整改时间，默认检查日期+7天
             */
            dueDate: string;
            /** @description 复查人员 */
            recheckPerson?: string | null;
            /** @description 整改前图片 uuid 列表 */
            beforeImageIds?: string[];
            status: components["schemas"]["HazardStatus"];
            /** @description 整改后图片 uuid 列表 */
            afterImageIds?: string[];
            /**
             * Format: int64
             * @description 隐患类型 id（=「大类+小类」组合行 id）
             */
            typeId: number;
            /** @description 隐患类型大类名称（JOIN 返回） */
            typeMajor: string;
            /** @description 隐患类型小类名称（JOIN 返回） */
            typeMinor: string;
            level: components["schemas"]["HazardLevel"];
            remark?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        HazardCreateRequest: {
            /** @default 华星现场 */
            inspectionArea: string;
            /**
             * Format: date
             * @description 缺省=今天
             */
            inspectionDate?: string;
            /** @default 电气自查 */
            inspector: string;
            /** @description 隐患描述（必填） */
            description: string;
            suggestion?: string | null;
            /**
             * Format: int64
             * @description 责任单位 id（必填，责任人由此关联）
             */
            unitId: number;
            /**
             * Format: date
             * @description 缺省=检查日期+7天
             */
            dueDate?: string;
            /** @description 缺省=检查人员 */
            recheckPerson?: string | null;
            beforeImageIds?: string[];
            /** @default 待整改 */
            status: components["schemas"]["HazardStatus"];
            afterImageIds?: string[];
            /**
             * Format: int64
             * @description 隐患类型组合行 id（必填，须已存在于 /hazard-types）
             */
            typeId: number;
            /** @default 一般隐患 */
            level: components["schemas"]["HazardLevel"];
            remark?: string | null;
        };
        /** @description 全部字段可选，仅更新提供的字段 */
        HazardUpdateRequest: {
            inspectionArea?: string;
            /** Format: date */
            inspectionDate?: string;
            inspector?: string;
            description?: string;
            suggestion?: string | null;
            /** Format: int64 */
            unitId?: number;
            /** Format: date */
            dueDate?: string;
            recheckPerson?: string | null;
            beforeImageIds?: string[];
            status?: components["schemas"]["HazardStatus"];
            afterImageIds?: string[];
            /**
             * Format: int64
             * @description 隐患类型组合行 id
             */
            typeId?: number;
            level?: components["schemas"]["HazardLevel"];
            remark?: string | null;
        };
        HazardListResponse: {
            items: components["schemas"]["Hazard"][];
            pagination: components["schemas"]["Pagination"];
        };
        Pagination: {
            /** @description 当前页 */
            page: number;
            /** @description 每页条数 */
            pageSize: number;
            /**
             * Format: int64
             * @description 总条数
             */
            total: number;
        };
        HazardStats: {
            /** @description 待整改数 */
            pending: number;
            /** @description 整改受阻数 */
            blocked: number;
            /** @description 已整改数 */
            done: number;
            /** @description 逾期未整改数（dueDate 早于今天且状态非已整改） */
            overdue: number;
        };
        ResponsibleUnit: {
            /** Format: int64 */
            id: number;
            /** @description 责任单位名称 */
            name: string;
            /** @description 责任人（一一对应） */
            person: string;
            remark?: string | null;
            /**
             * @description 0=停用 1=启用
             * @enum {integer}
             */
            status: 0 | 1;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UnitCreateRequest: {
            name: string;
            person: string;
            remark?: string | null;
            /**
             * @default 1
             * @enum {integer}
             */
            status: 0 | 1;
        };
        UnitUpdateRequest: {
            name?: string;
            person?: string;
            remark?: string | null;
            /** @enum {integer} */
            status?: 0 | 1;
        };
        HazardType: {
            /** Format: int64 */
            id: number;
            /** @description 大类（组内去重展示，也支持直接输入新大类） */
            major: string;
            /** @description 小类 */
            minor: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description 每次新增需同时提供大类与小类；同一「大类+小类」组合唯一 */
        HazardTypeCreateRequest: {
            /** @description 大类 */
            major: string;
            /** @description 小类 */
            minor: string;
        };
        HazardTypeUpdateRequest: {
            major?: string;
            minor?: string;
        };
        ImageInfo: {
            /** @description uuid（32 位十六进制，其他表只存此值） */
            id: string;
            /** @description SHA-256 摘要（十六进制，去重依据） */
            digest: string;
            mimeType: string;
            /** Format: int64 */
            sizeBytes: number;
            width?: number | null;
            height?: number | null;
            /** @description 相对路径，形如 /api/v1/images/860e... */
            url: string;
            /** @description 相对路径，形如 /api/v1/images/860e.../thumbnail */
            thumbnailUrl: string;
            /**
             * @description 是否命中既有摘要（未重复保存）
             * @default false
             */
            duplicate: boolean;
        };
        /** @description 附件列表项（不含 digest 细节，附带隐患引用计数） */
        ImageSummary: {
            /** @description uuid（32 位十六进制） */
            id: string;
            mimeType: string;
            /** Format: int64 */
            sizeBytes: number;
            width?: number | null;
            height?: number | null;
            /** @description 被多少条隐患记录引用（整改前/整改后图片合计） */
            refCount: number;
            /** Format: date-time */
            createdAt: string;
            url: string;
            thumbnailUrl: string;
        };
        ImageListResponse: {
            items: components["schemas"]["ImageSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
    };
    responses: {
        /** @description 未认证或令牌无效/过期 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 请求体/参数错误 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 业务校验失败（如分类不属于类型、责任单位无责任人） */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源被引用无法删除 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功，返回 JWT 令牌 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listHazards: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                status?: components["schemas"]["HazardStatus"];
                level?: components["schemas"]["HazardLevel"];
                /** @description 隐患类型组合行 id（按大类/小类过滤，需先查 /hazard-types 得到行 id） */
                typeId?: number;
                unitId?: number;
                area?: string;
                /** @description 模糊匹配 隐患描述/建议整改方案/备注/检查区域/检查人员/责任人 */
                keyword?: string;
                /** @description 检查日期起（含） */
                dateFrom?: string;
                /** @description 检查日期止（含） */
                dateTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分页结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HazardListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createHazard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HazardCreateRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hazard"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getHazardStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 统计结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HazardStats"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getHazard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hazard"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateHazard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HazardUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hazard"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    deleteHazard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listUnits: {
        parameters: {
            query?: {
                keyword?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 单位列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsibleUnit"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createUnit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnitCreateRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsibleUnit"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    updateUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnitUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsibleUnit"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listHazardTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 类型列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HazardType"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createHazardType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HazardTypeCreateRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HazardType"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
        };
    };
    updateHazardType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HazardTypeUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HazardType"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    deleteHazardType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listImages: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                /** @description 为 true 时仅返回未被任何隐患引用的附件 */
                onlyUnused?: boolean;
                /** @description 按 uuid / SHA-256 摘要前缀匹配 */
                keyword?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分页结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    uploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description 图片文件，白名单 jpeg/png/webp/gif，默认上限 10MB
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 上传成功（duplicate=true 表示命中既有摘要） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageInfo"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 图片二进制 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                    "image/gif": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getImageThumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 缩略图二进制（JPEG） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
